# you can read more about security in the related section of the documentation
# http://symfony.com/doc/current/book/security.html
security:
    # http://symfony.com/doc/current/book/security.html#encoding-the-user-s-password
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    # http://symfony.com/doc/current/book/security.html#hierarchical-roles
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }                           
        hwi:                               
            id: hwi_oauth.user.provider    
    # the main part of the security, where you can set up firewalls
    # for specific sections of your app
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        # the login page has to be accessible for everybody
        demo_login:
            pattern:  ^/demo/secured/login$
            security: false
        
        # secures part of the application
        secured_area:
            pattern:    ^/
            oauth:
                provider: fos_userbundle
                resource_owners:
                    google: /security/login_google
                check_path: _security_check
                login_path: /security/login
                failure_path: /security/login
                oauth_user_provider:
                    service: my_user_provider

            logout:
                path:           /security/logout
                target:         /security/login #where to go after logout
            
            # Turn on anonymous for testings need.
            anonymous: ~

    # with these settings you can restrict or allow access for different parts
    # of your application based on roles, ip, host or methods
    # http://symfony.com/doc/current/cookbook/security/access_control.html
    access_control:
        - { path: ^/security/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/security/connect/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/demo/secured/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_USER }
        - { path: ^/, roles: ROLE_USER }