services:
      measure_collection_type:
        class:        Sportacus\CoreBundle\Form\Type\MeasureCollectionType
        arguments:    [doctrine]
#    sportacus_core.example:
#        class: Sportacus\CoreBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
